-- H2 测试数据库 schema
-- 使用 H2 兼容的语法

-- 1. 视频分析任务表
CREATE TABLE IF NOT EXISTS video_analysis_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    call_id VARCHAR(64) NOT NULL,
    content_id VARCHAR(64) NOT NULL,
    video_url VARCHAR(2048) NOT NULL,
    cover_url VARCHAR(2048),
    analysis_type VARCHAR(32) DEFAULT 'STANDARD',
    user_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count INT DEFAULT 0,
    trace_id VARCHAR(64),
    prompt_modules VARCHAR(4096),
    prompt_snapshot CLOB,
    result_json CLOB,
    moderation_result VARCHAR(16),
    overall_confidence DOUBLE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    error_message VARCHAR(2048)
);

CREATE INDEX IF NOT EXISTS idx_video_task_call_id ON video_analysis_task(call_id);
CREATE INDEX IF NOT EXISTS idx_video_task_status ON video_analysis_task(status);
CREATE INDEX IF NOT EXISTS idx_video_task_created_at ON video_analysis_task(created_at);

-- 2. 违规事件表
CREATE TABLE IF NOT EXISTS violation_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64),
    call_id VARCHAR(64) NOT NULL,
    user_id BIGINT,
    content_id VARCHAR(64),
    violation_type VARCHAR(50) NOT NULL,
    confidence DOUBLE NOT NULL,
    evidence VARCHAR(2048) NOT NULL,
    start_sec INT NOT NULL,
    end_sec INT NOT NULL,
    prompt_version VARCHAR(20),
    model_version VARCHAR(20),
    processed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_violation_event_call_id ON violation_event(call_id);
CREATE INDEX IF NOT EXISTS idx_violation_event_task_id ON violation_event(task_id);
CREATE INDEX IF NOT EXISTS idx_violation_event_processed ON violation_event(processed);

-- 3. 内容审核记录表
CREATE TABLE IF NOT EXISTS moderation_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id VARCHAR(64) NOT NULL UNIQUE,
    content_id VARCHAR(64) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    moderation_result VARCHAR(20) NOT NULL,
    violation_types VARCHAR(2048),
    confidence DOUBLE,
    reviewer_id VARCHAR(64),
    review_comment VARCHAR(2048),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_moderation_content_id ON moderation_record(content_id);
CREATE INDEX IF NOT EXISTS idx_moderation_result ON moderation_record(moderation_result);
CREATE INDEX IF NOT EXISTS idx_moderation_created_at ON moderation_record(created_at);
